### ISSUE TITLE
/api をルーティングの先頭に加える

### ISSUE THREAD

**Issue by karintou8710** [HumanCCompilerContest/HCCC_Infra#2]
ルーティング詳細はNotionの「システム構成」を参照してください。

**Comment by Alignof** [comment]
https://github.com/Alignof/HCCC_Infra/commit/f081b8b94c75a98661d11f380dcd67a4778a55b1
closeのかしこま！
![image](https://user-images.githubusercontent.com/43988093/201509320-685b5340-3cb5-4534-af2d-6d48bc721c54.png)
